### ISSUE TITLE
兄弟，您的bootloader链接好像失效了，您能发给我一个吗？先谢谢了

### ISSUE THREAD

**Issue by latincompass** [luantty2/nRF52840-instruction#1]
兄弟，您的nrfmicro方案n52840双模bootloader链接好像失效了，您能发给我一个吗？先谢谢了

**Comment by luantty2** [comment]
[pca10056_bootloader-0.2.10_s140_6.1.1.hex](https://github.com/joric/nrfmicro/wiki/Software#Bootloader)

**Comment by latincompass** [comment]
多谢您，太感谢了，研究研究，多和您请教
