### ISSUE TITLE
环境的测试问题

### ISSUE THREAD

**Issue by Czzr** [luantty2/nRF52840-instruction#18]
搭完环境测试一直不通过，请问是缺了什么吗
![屏幕截图 2021-07-31 213859](https://user-images.githubusercontent.com/65123619/127741844-a530f128-336e-43d6-912c-82c43120d159.png)

**Comment by H-QYan** [comment]
应该是前面的sdk位置需要填对

**Comment by Czzr** [comment]
> 应该是前面的sdk位置需要填对

![屏幕截图 2021-08-11 230650](https://user-images.githubusercontent.com/65123619/129054528-06c006ed-bcf6-4a04-b092-e5da1e2b728d.png)
应该没错吧  能看看你的吗

搞定了 谢谢
