### ISSUE TITLE
nrf52840能支持104键吗？

### ISSUE THREAD

**Issue by eos21** [luantty2/nRF52840-instruction#2]
nrf52840可用GPIO有多少？能支持104键吗？

**Comment by luantty2** [comment]
信驰达的52840全引脚引出模块可以做104，亿佰特52840引脚不够。
![PHOTO](https://i.imgur.com/7bC37xv.jpg)

**Comment by eos21** [comment]
如果采用信驰达的52840重新设计PCB，固件方面需要改动的地方有哪些？如有时间请赐教。

**Comment by luantty2** [comment]
我认为只需要定义那些亿百特52840上面的引脚没有的引脚（在board/custom_board.h里面自己定义）即可。但是我还没有测试过除了亿百特之外的其他模块，不能给你更具体的结论，可能还会遇到其他坑。
此外，[Holyiot](https://item.taobao.com/item.htm?id=568552917727)也有一个引脚够数的模块。

**Comment by eos21** [comment]
如果省略掉RGB灯、OLED显示等非必要IO引脚，E73最多能有多少GPIO可以用于驱动键盘矩阵？

**Comment by luantty2** [comment]
23个。
BOOT,DFU两个引脚也可以用作IO，但是我没有测试过，算上这两个一共25个。
如果再节约一点：
把LED指示灯（1，10）也用作IO，则一共26个。
不要电量监测引脚（0，04），一共27个。
不要电池开关监测（0，26），一共28个。
即便如此用28个引脚做104键还是有点吃紧。

**Comment by eos21** [comment]
19*6=114，25个IO就够用了啊，这样的话E73还是可以驱动104以上键盘的。 另外E73你是直接找厂家贴片的还是自己焊？

**Comment by luantty2** [comment]
自己焊

**Comment by eos21** [comment]
厉害啊，模块背面的那些引脚怎么焊啊？请指教，或者推荐一下焊接方法文章。

**Comment by luantty2** [comment]
PCB上有开孔，从背面就可以焊。
只要注意把模块背面引脚用烙铁上一层薄锡，就不太会虚焊。

**Comment by myst729** [comment]
> 19*6=114，25个IO就够用了啊，这样的话E73还是可以驱动104以上键盘的。 另外E73你是直接找厂家贴片的还是自己焊？

用duplex grid布矩阵可以做成10*12，还能剩一个给大小写指示灯 https://wiki.ai03.com/books/pcb-design/page/matrices-and-duplex-matrix
